Metrics/LineLength:
  Max: 200
Style/SignalException:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Max: 42
Style/NumericLiterals:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 12
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  # don't require classes to be documented
  Enabled: false
CollectionMethods:
  # don't prefer map to collect, recuce to inject
  Enabled: false
Encoding:
  # no need to always specify encoding
  Enabled: false
StringLiterals:
  # use single or double-quoted strings, as you please
  Enabled: false
Void:
  # == operator used in void context in specs
  Enabled: false
SignalException:
  # prefer raise to fail
  EnforcedStyle: only_raise
RaiseArgs:
  # don't care for what kind of raise
  Enabled: false
